{"name": "test_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_rerun.py:17: AssumptionFailure\n>>\tpytest.assume(1 == 4)\nAssertionError: assert False\n\ntest_rerun.py:18: AssumptionFailure\n>>\tpytest.assume(2 == 4)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_rerun.py:17: AssumptionFailure\nE               >>\tpytest.assume(1 == 4)\nE               AssertionError: assert False\nE               \nE               test_rerun.py:18: AssumptionFailure\nE               >>\tpytest.assume(2 == 4)\nE               AssertionError: assert False\n\n/opt/homebrew/lib/python3.9/site-packages/six.py:718: FailedAssumption"}, "attachments": [{"name": "stdout", "source": "e4955b51-2f59-4722-9959-10f3bfc1deea-attachment.txt", "type": "text/plain"}], "start": 1622387567363, "stop": 1622387567363, "uuid": "07618701-4932-4786-b392-264b1f8c0a80", "historyId": "fc94f8b02933aaf2686a717727f5faf1", "testCaseId": "17e1f2569bee284b29fc37871bf601b0", "fullName": "test_rerun#test_assume", "labels": [{"name": "suite", "value": "test_rerun"}, {"name": "host", "value": "mozhenraodeMacBook-Air.local"}, {"name": "thread", "value": "7706-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_rerun"}]}